Repository opensearch-project/ml-commons-dashboards, pull requests merged in 2023-08, with the labels that each got.

#239 Add source field to distinguish local and external model
  public/apis/model.ts
  public/components/monitoring/model_deployment_table.tsx
  public/components/monitoring/tests/model_deployment_table.test.tsx
  public/components/monitoring/tests/use_monitoring.test.ts
  public/components/monitoring/use_monitoring.ts
  public/components/preview_panel/__tests__/preview_panel.test.tsx
  public/components/preview_panel/index.tsx
  server/routes/model_router.ts
  server/services/model_service.ts
  server/services/utils/model.ts
Labels: backport 2.x, backport 2.9

#238 Fix no model show up when search a model
  public/components/monitoring/tests/use_monitoring.test.ts
  public/components/monitoring/use_monitoring.ts
Labels: backport 2.x, backport 2.9

#227 Feat mitigate to oui style variables
  public/ace-themes/sql_console.js
  public/components/monitoring/index.scss
  public/components/monitoring/index.tsx
  public/components/monitoring/model_deployment_table.tsx
  public/components/monitoring/tests/index.test.tsx
  public/components/preview_panel/index.tsx
  public/components/preview_panel/nodes_table.scss
  public/index.scss
  public/index.ts
Labels: backport 2.x, v2.10.0

#252 update preview panel for external models
  public/components/preview_panel/__tests__/connector_details.test.tsx
  public/components/preview_panel/__tests__/nodes_table.test.tsx
  public/components/preview_panel/__tests__/preview_panel.test.tsx
  public/components/preview_panel/connector_details.tsx
  public/components/preview_panel/index.tsx
  public/components/preview_panel/nodes_table.tsx
Labels: backport 2.x
