Repository opensearch-project/ml-commons-dashboards, pull requests merged in 2024-09, with the labels that each got.

#355 Align font size and style
  public/components/monitoring/model_deployment_table.tsx
  public/components/preview_panel/connector_details.tsx
  public/components/preview_panel/index.tsx
  public/components/preview_panel/nodes_table.tsx
Labels: backport 2.x, v2.17.0

#358 Fix connector router response 500
  server/routes/__tests__/connector_router.test.ts
  server/routes/connector_router.ts
  server/routes/router.mock.ts
Labels: backport 2.x, v2.17.0

#365 doc: add release notes for 2.17
  release-notes/opensearch-ml-commons-dashboards.release-notes-2.17.0.0.md
Labels: backport 2.x, v2.17.0, backport 2.17

#369 Fix category order and description in data administration landing page
  public/plugin.ts
  release-notes/opensearch-ml-commons-dashboards.release-notes-2.17.0.0.md
Labels: backport 2.x

#378 Add release notes for 2.17.1.0
  release-notes/opensearch-ml-commons-dashboards.release-notes-2.17.1.0.md
Labels: backport 2.x, backport 2.17, v2.17.1

#377 Reduce machine learning table spacing when new home page enabled
  public/components/common/refresh_interval.tsx
  public/components/monitoring/index.tsx
  public/components/monitoring/monitoring_page_header.tsx
Labels: backport 2.x, v2.18.0
